package io.libp2p.pubsub.gossip

import com.google.protobuf.Descriptors.Descriptor
import com.google.protobuf.Descriptors.FieldDescriptor
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import pubsub.pb.Rpc

class RpcSchemaAccountingTest {

    @Test
    fun `RPC schema changes require reviewing inbound and outbound accounting`() {
        val reachable = linkedMapOf<String, Descriptor>()

        fun visit(message: Descriptor) {
            if (reachable.putIfAbsent(message.fullName, message) != null) return
            message.fields
                .filter { it.javaType == FieldDescriptor.JavaType.MESSAGE }
                .forEach { visit(it.messageType) }
        }
        visit(Rpc.RPC.getDescriptor())

        fun fieldSignature(field: FieldDescriptor): String {
            val cardinality = when {
                field.isRepeated -> "*"
                field.isRequired -> "!"
                else -> "?"
            }
            val target = when (field.javaType) {
                FieldDescriptor.JavaType.MESSAGE -> ":${field.messageType.fullName}"
                FieldDescriptor.JavaType.ENUM -> ":${field.enumType.fullName}"
                else -> ""
            }
            val packed = if (field.isPacked) ":packed" else ""
            val oneof = field.containingOneof?.let { ":oneof=${it.name}" } ?: ""
            return "${field.number}:${field.name}:${field.type}$cardinality$target$packed$oneof"
        }

        val actual = reachable.values.sortedBy { it.fullName }.joinToString("\n") {
            val syntax = it.file.toProto().syntax.ifEmpty { "proto2" }
            val fields = it.fields.sortedBy { field -> field.number }
                .joinToString(" ", transform = ::fieldSignature)
            "${it.fullName} [$syntax] {$fields}"
        }

        // Fixed snapshot, not regenerated by this test: changes must trigger an accounting review.
        // ? = optional, * = repeated, ! = required. Empty reachable messages are included too.
        val expected = """
            pubsub.pb.ControlExtensions [proto2] {10:partialMessages:BOOL? 6492434:testExtension:BOOL?}
            pubsub.pb.ControlGraft [proto2] {1:topicID:STRING?}
            pubsub.pb.ControlIDontWant [proto2] {1:messageIDs:BYTES*}
            pubsub.pb.ControlIHave [proto2] {1:topicID:STRING? 2:messageIDs:BYTES*}
            pubsub.pb.ControlIWant [proto2] {1:messageIDs:BYTES*}
            pubsub.pb.ControlMessage [proto2] {1:ihave:MESSAGE*:pubsub.pb.ControlIHave 2:iwant:MESSAGE*:pubsub.pb.ControlIWant 3:graft:MESSAGE*:pubsub.pb.ControlGraft 4:prune:MESSAGE*:pubsub.pb.ControlPrune 5:idontwant:MESSAGE*:pubsub.pb.ControlIDontWant 6:extensions:MESSAGE?:pubsub.pb.ControlExtensions}
            pubsub.pb.ControlPrune [proto2] {1:topicID:STRING? 2:peers:MESSAGE*:pubsub.pb.PeerInfo 3:backoff:UINT64?}
            pubsub.pb.Message [proto2] {1:from:BYTES? 2:data:BYTES? 3:seqno:BYTES? 4:topicIDs:STRING* 5:signature:BYTES? 6:key:BYTES?}
            pubsub.pb.PartialMessagesExtension [proto2] {1:topicID:STRING? 2:groupID:BYTES? 3:partialMessage:BYTES? 4:partsMetadata:BYTES?}
            pubsub.pb.PeerInfo [proto2] {1:peerID:BYTES? 2:signedPeerRecord:BYTES?}
            pubsub.pb.RPC [proto2] {1:subscriptions:MESSAGE*:pubsub.pb.RPC.SubOpts 2:publish:MESSAGE*:pubsub.pb.Message 3:control:MESSAGE?:pubsub.pb.ControlMessage 10:partial:MESSAGE?:pubsub.pb.PartialMessagesExtension 6492434:testExtension:MESSAGE?:pubsub.pb.TestExtension}
            pubsub.pb.RPC.SubOpts [proto2] {1:subscribe:BOOL? 2:topicid:STRING? 3:requestsPartial:BOOL? 4:supportsSendingPartial:BOOL?}
            pubsub.pb.TestExtension [proto2] {}
        """.trimIndent()

        assertThat(actual)
            .`as`("RPC schema changed: review RpcMessageCountValidator and part field counts before updating the snapshot")
            .isEqualTo(expected)
    }
}
