// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voucher.proto

package io.libp2p.protocol.circuit.pb;

public final class VoucherOuterClass {
  private VoucherOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface VoucherOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:io.libp2p.protocol.circuit.pb.Voucher)
      com.google.protobuf.MessageOrBuilder {

    /** <code>required bytes relay = 1;</code> */
    boolean hasRelay();

    /** <code>required bytes relay = 1;</code> */
    com.google.protobuf.ByteString getRelay();

    /** <code>required bytes peer = 2;</code> */
    boolean hasPeer();

    /** <code>required bytes peer = 2;</code> */
    com.google.protobuf.ByteString getPeer();

    /** <code>required uint64 expiration = 3;</code> */
    boolean hasExpiration();

    /** <code>required uint64 expiration = 3;</code> */
    long getExpiration();
  }

  /** Protobuf type {@code io.libp2p.protocol.circuit.pb.Voucher} */
  public static final class Voucher extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:io.libp2p.protocol.circuit.pb.Voucher)
      VoucherOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Voucher.newBuilder() to construct.
    private Voucher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Voucher() {
      relay_ = com.google.protobuf.ByteString.EMPTY;
      peer_ = com.google.protobuf.ByteString.EMPTY;
      expiration_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Voucher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                bitField0_ |= 0x00000001;
                relay_ = input.readBytes();
                break;
              }
            case 18:
              {
                bitField0_ |= 0x00000002;
                peer_ = input.readBytes();
                break;
              }
            case 24:
              {
                bitField0_ |= 0x00000004;
                expiration_ = input.readUInt64();
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.libp2p.protocol.circuit.pb.VoucherOuterClass
          .internal_static_io_libp2p_protocol_circuit_pb_Voucher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.libp2p.protocol.circuit.pb.VoucherOuterClass
          .internal_static_io_libp2p_protocol_circuit_pb_Voucher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.class,
              io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.Builder.class);
    }

    private int bitField0_;
    public static final int RELAY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString relay_;

    /** <code>required bytes relay = 1;</code> */
    public boolean hasRelay() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /** <code>required bytes relay = 1;</code> */
    public com.google.protobuf.ByteString getRelay() {
      return relay_;
    }

    public static final int PEER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString peer_;

    /** <code>required bytes peer = 2;</code> */
    public boolean hasPeer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /** <code>required bytes peer = 2;</code> */
    public com.google.protobuf.ByteString getPeer() {
      return peer_;
    }

    public static final int EXPIRATION_FIELD_NUMBER = 3;
    private long expiration_;

    /** <code>required uint64 expiration = 3;</code> */
    public boolean hasExpiration() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /** <code>required uint64 expiration = 3;</code> */
    public long getExpiration() {
      return expiration_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRelay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPeer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExpiration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, relay_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, peer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, expiration_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, relay_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, peer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream.computeUInt64Size(3, expiration_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher)) {
        return super.equals(obj);
      }
      io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher other =
          (io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher) obj;

      boolean result = true;
      result = result && (hasRelay() == other.hasRelay());
      if (hasRelay()) {
        result = result && getRelay().equals(other.getRelay());
      }
      result = result && (hasPeer() == other.hasPeer());
      if (hasPeer()) {
        result = result && getPeer().equals(other.getPeer());
      }
      result = result && (hasExpiration() == other.hasExpiration());
      if (hasExpiration()) {
        result = result && (getExpiration() == other.getExpiration());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRelay()) {
        hash = (37 * hash) + RELAY_FIELD_NUMBER;
        hash = (53 * hash) + getRelay().hashCode();
      }
      if (hasPeer()) {
        hash = (37 * hash) + PEER_FIELD_NUMBER;
        hash = (53 * hash) + getPeer().hashCode();
      }
      if (hasExpiration()) {
        hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getExpiration());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /** Protobuf type {@code io.libp2p.protocol.circuit.pb.Voucher} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:io.libp2p.protocol.circuit.pb.Voucher)
        io.libp2p.protocol.circuit.pb.VoucherOuterClass.VoucherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return io.libp2p.protocol.circuit.pb.VoucherOuterClass
            .internal_static_io_libp2p_protocol_circuit_pb_Voucher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.libp2p.protocol.circuit.pb.VoucherOuterClass
            .internal_static_io_libp2p_protocol_circuit_pb_Voucher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.class,
                io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.Builder.class);
      }

      // Construct using io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        relay_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        peer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        expiration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return io.libp2p.protocol.circuit.pb.VoucherOuterClass
            .internal_static_io_libp2p_protocol_circuit_pb_Voucher_descriptor;
      }

      @java.lang.Override
      public io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher getDefaultInstanceForType() {
        return io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.getDefaultInstance();
      }

      @java.lang.Override
      public io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher build() {
        io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher buildPartial() {
        io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher result =
            new io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.relay_ = relay_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.peer_ = peer_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.expiration_ = expiration_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher) {
          return mergeFrom((io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher other) {
        if (other == io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher.getDefaultInstance())
          return this;
        if (other.hasRelay()) {
          setRelay(other.getRelay());
        }
        if (other.hasPeer()) {
          setPeer(other.getPeer());
        }
        if (other.hasExpiration()) {
          setExpiration(other.getExpiration());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRelay()) {
          return false;
        }
        if (!hasPeer()) {
          return false;
        }
        if (!hasExpiration()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.ByteString relay_ = com.google.protobuf.ByteString.EMPTY;

      /** <code>required bytes relay = 1;</code> */
      public boolean hasRelay() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /** <code>required bytes relay = 1;</code> */
      public com.google.protobuf.ByteString getRelay() {
        return relay_;
      }

      /** <code>required bytes relay = 1;</code> */
      public Builder setRelay(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        relay_ = value;
        onChanged();
        return this;
      }

      /** <code>required bytes relay = 1;</code> */
      public Builder clearRelay() {
        bitField0_ = (bitField0_ & ~0x00000001);
        relay_ = getDefaultInstance().getRelay();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString peer_ = com.google.protobuf.ByteString.EMPTY;

      /** <code>required bytes peer = 2;</code> */
      public boolean hasPeer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /** <code>required bytes peer = 2;</code> */
      public com.google.protobuf.ByteString getPeer() {
        return peer_;
      }

      /** <code>required bytes peer = 2;</code> */
      public Builder setPeer(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        peer_ = value;
        onChanged();
        return this;
      }

      /** <code>required bytes peer = 2;</code> */
      public Builder clearPeer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        peer_ = getDefaultInstance().getPeer();
        onChanged();
        return this;
      }

      private long expiration_;

      /** <code>required uint64 expiration = 3;</code> */
      public boolean hasExpiration() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /** <code>required uint64 expiration = 3;</code> */
      public long getExpiration() {
        return expiration_;
      }

      /** <code>required uint64 expiration = 3;</code> */
      public Builder setExpiration(long value) {
        bitField0_ |= 0x00000004;
        expiration_ = value;
        onChanged();
        return this;
      }

      /** <code>required uint64 expiration = 3;</code> */
      public Builder clearExpiration() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expiration_ = 0L;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:io.libp2p.protocol.circuit.pb.Voucher)
    }

    // @@protoc_insertion_point(class_scope:io.libp2p.protocol.circuit.pb.Voucher)
    private static final io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher();
    }

    public static io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<Voucher> PARSER =
        new com.google.protobuf.AbstractParser<Voucher>() {
          @java.lang.Override
          public Voucher parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Voucher(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Voucher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Voucher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.libp2p.protocol.circuit.pb.VoucherOuterClass.Voucher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_io_libp2p_protocol_circuit_pb_Voucher_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_libp2p_protocol_circuit_pb_Voucher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\rvoucher.proto\022\037io.libp2p.protocol.ci"
          + "rcuit.pb\":\n\007Voucher\022\r\n\005relay\030\001 \002(\014\022\014\n\004pe"
          + "er\030\002 \002(\014\022\022\n\nexpiration\030\003 \002(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_io_libp2p_protocol_circuit_pb_Voucher_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_io_libp2p_protocol_circuit_pb_Voucher_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_io_libp2p_protocol_circuit_pb_Voucher_descriptor,
            new java.lang.String[] {
              "Relay", "Peer", "Expiration",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
